project:
  type: book

book:
  title: "TP de Biométrie<br> Semestre 6<br>"
  author: "Benoît Simon-Bouhet"
  date: now
  date-format: "full"
  search: true
  downloads: pdf
  page-navigation: true
  repo-url: "https://github.com/besibo/BiometrieS6"
  chapters:
    - index.qmd
    - 01-OneSampleTests.qmd
    - 02-TwoSamplePairedTests.qmd
    - 03-TwoSampleTests.qmd
    - 04-ANOVA.qmd
    - 05-Regression.qmd
    - 06-PropTests.qmd
    - references.qmd

bibliography: all.bib
lang: fr
title-block-banner: true
reference-location: margin

language: 
  title-block-author-single: "Auteur"
  title-block-published: "Dernière Mise à jour"

format:
  html:
    theme: MyUnited.scss
    highlight-style: solarized
    # code-tools: 
    #   source: false
    #   toggle: true
    # code-fold: show
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-depth: 5
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    toc-depth: 4
  pdf:
    documentclass: scrreprt
    papersize: a4
    highlight-style: github
    code-block-bg: false
    code-block-border-left: "#31BAE9"
    code-depth: 5
    colorlinks: true
